# Formatting date and Time
from datetime import datetime
dt = datetime.today()
print(dt)
print(type(dt))
print()
newdt = dt.strftime("%B, %d, %Y")
print(newdt)
print(type(newdt))
print()
newdt1= dt.strftime("%d/%b/%Y")
print(newdt1)
print()
newdt2= dt.strftime("%d-%m-%Y")
print(newdt2)
print()
newdt3= dt.strftime("%H:%M:%S")
print(newdt3)
print()
newdt4= dt.strftime("%I:%M:%S")
print(newdt4)